#!/usr/bin/env bash
# This script displays a story for each user from /etc/passwd using while loop + IFS

while IFS=":" read -r username password uid gid fullname home shell; do
  echo "The user $username is part of $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $fullname"
done < /etc/passwd

