#!/usr/bin/env bash
# This script tells the story of each user in /etc/passwd

counter=1

while IFS=: read -r username password uid gid info home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $counter's place is protected by the passcode $password, more info about the user here: $info"
    counter=$((counter + 1))
done < /etc/passwd
