#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, sorted by occurrences

awk '
{
  key = $1 " " $9
  count[key]++
}
END {
  for (k in count) {
    split(k, a, " ")
    printf "%d %s %s\n", count[k], a[1], a[2]
  }
}
' apache-access.log | sort -nr

